version: '3.8'

services:
  app:
    build: .
    container_name: orders-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/ordersdb
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongodb-orders
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
